---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lstocks3/vidacellenlaweb.com/
    - /bin/mkdir -p ${DEPLOYPATH}assets/css
    - /bin/mkdir -p ${DEPLOYPATH}assets/js
    - /bin/mkdir -p ${DEPLOYPATH}assets/img/logo
    - /bin/cp -f index.html ${DEPLOYPATH}index.html
    - /bin/cp -f robots.txt ${DEPLOYPATH}robots.txt
    - /bin/cp -f sitemap.xml ${DEPLOYPATH}sitemap.xml
    - /bin/cp -f assets/css/style.css ${DEPLOYPATH}assets/css/style.css
    - /bin/cp -f assets/js/main.js ${DEPLOYPATH}assets/js/main.js
    - /bin/cp -f assets/img/logo/vidacell-logo.png ${DEPLOYPATH}assets/img/logo/vidacell-logo.png
    - /bin/cp -f assets/img/logo/favicon.png ${DEPLOYPATH}assets/img/logo/favicon.png
